//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ANDAPPEntities : DbContext
    {
        public ANDAPPEntities()
            : base("name=ANDAPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MODEL_ANDAPP> MODEL_ANDAPP { get; set; }
        public virtual DbSet<RTOMASTER> RTOMASTERs { get; set; }
        public virtual DbSet<STATEMASTER> STATEMASTERs { get; set; }
        public virtual DbSet<INSURANCECOMPANY> INSURANCECOMPANies { get; set; }
        public virtual DbSet<ADDONMASTER> ADDONMASTERs { get; set; }
        public virtual DbSet<INSURANCEVARIANTMASTER> INSURANCEVARIANTMASTERs { get; set; }
        public virtual DbSet<NOMINEE_RELATIONSHIP> NOMINEE_RELATIONSHIP { get; set; }
        public virtual DbSet<OCCUPATION> OCCUPATIONs { get; set; }
        public virtual DbSet<VARIANT_ANDAPP> VARIANT_ANDAPP { get; set; }
        public virtual DbSet<MAKE_ANDAPP> MAKE_ANDAPP { get; set; }
        public virtual DbSet<PREVIOUS_INSURER_MAPPING> PREVIOUS_INSURER_MAPPING { get; set; }
        public virtual DbSet<VW_GENERATEDQUOTAIONLIST_POSPWISE> VW_GENERATEDQUOTAIONLIST_POSPWISE { get; set; }
        public virtual DbSet<SALUTATIONMASTER> SALUTATIONMASTERs { get; set; }
        public virtual DbSet<MARITALSTATUSMASTER> MARITALSTATUSMASTERs { get; set; }
        public virtual DbSet<FINANCERMASTER> FINANCERMASTERs { get; set; }
        public virtual DbSet<QA_LOGIN_MASTER> QA_LOGIN_MASTER { get; set; }
        public virtual DbSet<POLICY_ENQUIRY> POLICY_ENQUIRY { get; set; }
        public virtual DbSet<COMPANY_WISE_STATE_MASTER> COMPANY_WISE_STATE_MASTER { get; set; }
        public virtual DbSet<icici_paymenttagging> icici_paymenttagging { get; set; }
        public virtual DbSet<COMPANY_WISE_STATE_CITY_AREA_MASTER> COMPANY_WISE_STATE_CITY_AREA_MASTER { get; set; }
        public virtual DbSet<POSPMASTER> POSPMASTERs { get; set; }
        public virtual DbSet<VW_ExamPassDate_ForAndReport> VW_ExamPassDate_ForAndReport { get; set; }
        public virtual DbSet<VW_ExamPassDate_ForAndReport_LI> VW_ExamPassDate_ForAndReport_LI { get; set; }
        public virtual DbSet<VW_TOP10MAKE> VW_TOP10MAKE { get; set; }
        public virtual DbSet<RTOMASTER_ANDAPP> RTOMASTER_ANDAPP { get; set; }
        public virtual DbSet<Payment_Parameter> Payment_Parameter { get; set; }
        public virtual DbSet<PospCity_Mapping> PospCity_Mapping { get; set; }
        public virtual DbSet<VW_POLICYDETAILSMASTER> VW_POLICYDETAILSMASTER { get; set; }
        public virtual DbSet<COMPANY_WISE_RTO_MASTER> COMPANY_WISE_RTO_MASTER { get; set; }
    
        public virtual ObjectResult<GET_INSCOMPANYDATA_BY_VARIANT_Result> GET_INSCOMPANYDATA_BY_VARIANT(Nullable<long> p_variantid, Nullable<long> p_companyid)
        {
            var p_variantidParameter = p_variantid.HasValue ?
                new ObjectParameter("p_variantid", p_variantid) :
                new ObjectParameter("p_variantid", typeof(long));
    
            var p_companyidParameter = p_companyid.HasValue ?
                new ObjectParameter("p_companyid", p_companyid) :
                new ObjectParameter("p_companyid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_INSCOMPANYDATA_BY_VARIANT_Result>("GET_INSCOMPANYDATA_BY_VARIANT", p_variantidParameter, p_companyidParameter);
        }
    
        public virtual ObjectResult<GET_INSCOMPANYDATA_BY_VARIANT1_Result> GET_INSCOMPANYDATA_BY_VARIANT1(Nullable<long> p_variantid, Nullable<long> p_companyid)
        {
            var p_variantidParameter = p_variantid.HasValue ?
                new ObjectParameter("p_variantid", p_variantid) :
                new ObjectParameter("p_variantid", typeof(long));
    
            var p_companyidParameter = p_companyid.HasValue ?
                new ObjectParameter("p_companyid", p_companyid) :
                new ObjectParameter("p_companyid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_INSCOMPANYDATA_BY_VARIANT1_Result>("GET_INSCOMPANYDATA_BY_VARIANT1", p_variantidParameter, p_companyidParameter);
        }
    
        public virtual ObjectResult<SP_QUALIFYCOMPANY> SP_QUALIFYCOMPANY(Nullable<bool> p_isbreaking, Nullable<long> p_rtoid, Nullable<long> p_variantid)
        {
            var p_isbreakingParameter = p_isbreaking.HasValue ?
                new ObjectParameter("p_isbreaking", p_isbreaking) :
                new ObjectParameter("p_isbreaking", typeof(bool));
    
            var p_rtoidParameter = p_rtoid.HasValue ?
                new ObjectParameter("p_rtoid", p_rtoid) :
                new ObjectParameter("p_rtoid", typeof(long));
    
            var p_variantidParameter = p_variantid.HasValue ?
                new ObjectParameter("p_variantid", p_variantid) :
                new ObjectParameter("p_variantid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_QUALIFYCOMPANY>("SP_QUALIFYCOMPANY", p_isbreakingParameter, p_rtoidParameter, p_variantidParameter);
        }
    
        public virtual ObjectResult<string> SP_GETFUELTYPE_BY_MODELID(Nullable<long> p_modelid)
        {
            var p_modelidParameter = p_modelid.HasValue ?
                new ObjectParameter("p_modelid", p_modelid) :
                new ObjectParameter("p_modelid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GETFUELTYPE_BY_MODELID", p_modelidParameter);
        }
    
        public virtual ObjectResult<SP_GETFUELTYPE_BY_MODELID> SP_GETFUELTYPE_BY_MODELID1(Nullable<long> p_modelid)
        {
            var p_modelidParameter = p_modelid.HasValue ?
                new ObjectParameter("p_modelid", p_modelid) :
                new ObjectParameter("p_modelid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETFUELTYPE_BY_MODELID>("SP_GETFUELTYPE_BY_MODELID1", p_modelidParameter);
        }
    
        public virtual ObjectResult<SP_COMPANY_WISE_CITY_Result> SP_COMPANY_WISE_CITY(string p_company, Nullable<long> p_stateid)
        {
            var p_companyParameter = p_company != null ?
                new ObjectParameter("p_company", p_company) :
                new ObjectParameter("p_company", typeof(string));
    
            var p_stateidParameter = p_stateid.HasValue ?
                new ObjectParameter("p_stateid", p_stateid) :
                new ObjectParameter("p_stateid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_COMPANY_WISE_CITY_Result>("SP_COMPANY_WISE_CITY", p_companyParameter, p_stateidParameter);
        }
    
        public virtual ObjectResult<SP_COMPANY_WISE_MARITALSTATUS_Result> SP_COMPANY_WISE_MARITALSTATUS(Nullable<long> p_companyid)
        {
            var p_companyidParameter = p_companyid.HasValue ?
                new ObjectParameter("p_companyid", p_companyid) :
                new ObjectParameter("p_companyid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_COMPANY_WISE_MARITALSTATUS_Result>("SP_COMPANY_WISE_MARITALSTATUS", p_companyidParameter);
        }
    
        public virtual ObjectResult<SP_COMPANY_WISE_NOMINEERELATION_Result1> SP_COMPANY_WISE_NOMINEERELATION(Nullable<long> p_companyid)
        {
            var p_companyidParameter = p_companyid.HasValue ?
                new ObjectParameter("p_companyid", p_companyid) :
                new ObjectParameter("p_companyid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_COMPANY_WISE_NOMINEERELATION_Result1>("SP_COMPANY_WISE_NOMINEERELATION", p_companyidParameter);
        }
    
        public virtual ObjectResult<SP_COMPANY_WISE_OCCUPATION_Result1> SP_COMPANY_WISE_OCCUPATION(Nullable<long> p_companyid)
        {
            var p_companyidParameter = p_companyid.HasValue ?
                new ObjectParameter("p_companyid", p_companyid) :
                new ObjectParameter("p_companyid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_COMPANY_WISE_OCCUPATION_Result1>("SP_COMPANY_WISE_OCCUPATION", p_companyidParameter);
        }
    
        public virtual ObjectResult<SP_COMPANY_WISE_SALUTATION_Result> SP_COMPANY_WISE_SALUTATION(Nullable<long> p_companyid)
        {
            var p_companyidParameter = p_companyid.HasValue ?
                new ObjectParameter("p_companyid", p_companyid) :
                new ObjectParameter("p_companyid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_COMPANY_WISE_SALUTATION_Result>("SP_COMPANY_WISE_SALUTATION", p_companyidParameter);
        }
    
        public virtual ObjectResult<SP_COMPANY_WISE_FINANCERMASTER_Result> SP_COMPANY_WISE_FINANCERMASTER(Nullable<long> p_companyid)
        {
            var p_companyidParameter = p_companyid.HasValue ?
                new ObjectParameter("p_companyid", p_companyid) :
                new ObjectParameter("p_companyid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_COMPANY_WISE_FINANCERMASTER_Result>("SP_COMPANY_WISE_FINANCERMASTER", p_companyidParameter);
        }
    
        public virtual int SP_POLICY_ENQUIRYDETAILS(string enquiryno, string enquiryrequest, string enquiryresponse, Nullable<int> enquirytype, string firstquote, Nullable<long> enquiryby)
        {
            var enquirynoParameter = enquiryno != null ?
                new ObjectParameter("enquiryno", enquiryno) :
                new ObjectParameter("enquiryno", typeof(string));
    
            var enquiryrequestParameter = enquiryrequest != null ?
                new ObjectParameter("enquiryrequest", enquiryrequest) :
                new ObjectParameter("enquiryrequest", typeof(string));
    
            var enquiryresponseParameter = enquiryresponse != null ?
                new ObjectParameter("enquiryresponse", enquiryresponse) :
                new ObjectParameter("enquiryresponse", typeof(string));
    
            var enquirytypeParameter = enquirytype.HasValue ?
                new ObjectParameter("enquirytype", enquirytype) :
                new ObjectParameter("enquirytype", typeof(int));
    
            var firstquoteParameter = firstquote != null ?
                new ObjectParameter("firstquote", firstquote) :
                new ObjectParameter("firstquote", typeof(string));
    
            var enquirybyParameter = enquiryby.HasValue ?
                new ObjectParameter("enquiryby", enquiryby) :
                new ObjectParameter("enquiryby", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_POLICY_ENQUIRYDETAILS", enquirynoParameter, enquiryrequestParameter, enquiryresponseParameter, enquirytypeParameter, firstquoteParameter, enquirybyParameter);
        }
    
        public virtual ObjectResult<SP_REQUEST_RESPONSE_MASTER_Result> SP_REQUEST_RESPONSE_MASTER(string p_mode, string p_enquiryid, Nullable<int> p_companyid, string p_request, string p_response)
        {
            var p_modeParameter = p_mode != null ?
                new ObjectParameter("p_mode", p_mode) :
                new ObjectParameter("p_mode", typeof(string));
    
            var p_enquiryidParameter = p_enquiryid != null ?
                new ObjectParameter("p_enquiryid", p_enquiryid) :
                new ObjectParameter("p_enquiryid", typeof(string));
    
            var p_companyidParameter = p_companyid.HasValue ?
                new ObjectParameter("p_companyid", p_companyid) :
                new ObjectParameter("p_companyid", typeof(int));
    
            var p_requestParameter = p_request != null ?
                new ObjectParameter("p_request", p_request) :
                new ObjectParameter("p_request", typeof(string));
    
            var p_responseParameter = p_response != null ?
                new ObjectParameter("p_response", p_response) :
                new ObjectParameter("p_response", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_REQUEST_RESPONSE_MASTER_Result>("SP_REQUEST_RESPONSE_MASTER", p_modeParameter, p_enquiryidParameter, p_companyidParameter, p_requestParameter, p_responseParameter);
        }
    
        public virtual int SP_REQUEST_RESPONSE_API_MASTER(string p_enquiryid, Nullable<int> p_companyid, string p_request, string p_response)
        {
            var p_enquiryidParameter = p_enquiryid != null ?
                new ObjectParameter("p_enquiryid", p_enquiryid) :
                new ObjectParameter("p_enquiryid", typeof(string));
    
            var p_companyidParameter = p_companyid.HasValue ?
                new ObjectParameter("p_companyid", p_companyid) :
                new ObjectParameter("p_companyid", typeof(int));
    
            var p_requestParameter = p_request != null ?
                new ObjectParameter("p_request", p_request) :
                new ObjectParameter("p_request", typeof(string));
    
            var p_responseParameter = p_response != null ?
                new ObjectParameter("p_response", p_response) :
                new ObjectParameter("p_response", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REQUEST_RESPONSE_API_MASTER", p_enquiryidParameter, p_companyidParameter, p_requestParameter, p_responseParameter);
        }
    
        public virtual ObjectResult<SP_COMPANY_WISE_STATE_MASTER_Result> SP_COMPANY_WISE_STATE_MASTER(Nullable<long> p_companyid)
        {
            var p_companyidParameter = p_companyid.HasValue ?
                new ObjectParameter("p_companyid", p_companyid) :
                new ObjectParameter("p_companyid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_COMPANY_WISE_STATE_MASTER_Result>("SP_COMPANY_WISE_STATE_MASTER", p_companyidParameter);
        }
    
        public virtual int SP_Payment_Parameter(string enquiryno, Nullable<long> comid, string parname, string parvalue)
        {
            var enquirynoParameter = enquiryno != null ?
                new ObjectParameter("enquiryno", enquiryno) :
                new ObjectParameter("enquiryno", typeof(string));
    
            var comidParameter = comid.HasValue ?
                new ObjectParameter("comid", comid) :
                new ObjectParameter("comid", typeof(long));
    
            var parnameParameter = parname != null ?
                new ObjectParameter("parname", parname) :
                new ObjectParameter("parname", typeof(string));
    
            var parvalueParameter = parvalue != null ?
                new ObjectParameter("parvalue", parvalue) :
                new ObjectParameter("parvalue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Payment_Parameter", enquirynoParameter, comidParameter, parnameParameter, parvalueParameter);
        }
    
        public virtual ObjectResult<GET_Payment_Parameter_Result> GET_Payment_Parameter(string p_tran_id, Nullable<long> p_comid)
        {
            var p_tran_idParameter = p_tran_id != null ?
                new ObjectParameter("p_tran_id", p_tran_id) :
                new ObjectParameter("p_tran_id", typeof(string));
    
            var p_comidParameter = p_comid.HasValue ?
                new ObjectParameter("p_comid", p_comid) :
                new ObjectParameter("p_comid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_Payment_Parameter_Result>("GET_Payment_Parameter", p_tran_idParameter, p_comidParameter);
        }
    
        public virtual int SP_ICICI_PAYMENT_TAGGING(string p_EnqNo, string p_TransactionId, string p_PaymentAmount, string p_CustomerID, string p_PayerType, string p_ProposalNo, string p_dealid)
        {
            var p_EnqNoParameter = p_EnqNo != null ?
                new ObjectParameter("p_EnqNo", p_EnqNo) :
                new ObjectParameter("p_EnqNo", typeof(string));
    
            var p_TransactionIdParameter = p_TransactionId != null ?
                new ObjectParameter("p_TransactionId", p_TransactionId) :
                new ObjectParameter("p_TransactionId", typeof(string));
    
            var p_PaymentAmountParameter = p_PaymentAmount != null ?
                new ObjectParameter("p_PaymentAmount", p_PaymentAmount) :
                new ObjectParameter("p_PaymentAmount", typeof(string));
    
            var p_CustomerIDParameter = p_CustomerID != null ?
                new ObjectParameter("p_CustomerID", p_CustomerID) :
                new ObjectParameter("p_CustomerID", typeof(string));
    
            var p_PayerTypeParameter = p_PayerType != null ?
                new ObjectParameter("p_PayerType", p_PayerType) :
                new ObjectParameter("p_PayerType", typeof(string));
    
            var p_ProposalNoParameter = p_ProposalNo != null ?
                new ObjectParameter("p_ProposalNo", p_ProposalNo) :
                new ObjectParameter("p_ProposalNo", typeof(string));
    
            var p_dealidParameter = p_dealid != null ?
                new ObjectParameter("p_dealid", p_dealid) :
                new ObjectParameter("p_dealid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ICICI_PAYMENT_TAGGING", p_EnqNoParameter, p_TransactionIdParameter, p_PaymentAmountParameter, p_CustomerIDParameter, p_PayerTypeParameter, p_ProposalNoParameter, p_dealidParameter);
        }
    
        public virtual ObjectResult<SP_COMPANY_WISE_STATE_CITY_AREA_MASTER_Result> SP_COMPANY_WISE_STATE_CITY_AREA_MASTER(Nullable<long> p_companyid, Nullable<long> p_stateid, Nullable<long> p_cityid)
        {
            var p_companyidParameter = p_companyid.HasValue ?
                new ObjectParameter("p_companyid", p_companyid) :
                new ObjectParameter("p_companyid", typeof(long));
    
            var p_stateidParameter = p_stateid.HasValue ?
                new ObjectParameter("p_stateid", p_stateid) :
                new ObjectParameter("p_stateid", typeof(long));
    
            var p_cityidParameter = p_cityid.HasValue ?
                new ObjectParameter("p_cityid", p_cityid) :
                new ObjectParameter("p_cityid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_COMPANY_WISE_STATE_CITY_AREA_MASTER_Result>("SP_COMPANY_WISE_STATE_CITY_AREA_MASTER", p_companyidParameter, p_stateidParameter, p_cityidParameter);
        }
    
        public virtual int UpdatePOSPSecretKey(Nullable<long> pospid, string seceretkey)
        {
            var pospidParameter = pospid.HasValue ?
                new ObjectParameter("pospid", pospid) :
                new ObjectParameter("pospid", typeof(long));
    
            var seceretkeyParameter = seceretkey != null ?
                new ObjectParameter("seceretkey", seceretkey) :
                new ObjectParameter("seceretkey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePOSPSecretKey", pospidParameter, seceretkeyParameter);
        }
    
        public virtual int SP_TOP_MMV(Nullable<long> p_makeid, Nullable<long> p_modelid, Nullable<long> p_variantid)
        {
            var p_makeidParameter = p_makeid.HasValue ?
                new ObjectParameter("p_makeid", p_makeid) :
                new ObjectParameter("p_makeid", typeof(long));
    
            var p_modelidParameter = p_modelid.HasValue ?
                new ObjectParameter("p_modelid", p_modelid) :
                new ObjectParameter("p_modelid", typeof(long));
    
            var p_variantidParameter = p_variantid.HasValue ?
                new ObjectParameter("p_variantid", p_variantid) :
                new ObjectParameter("p_variantid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TOP_MMV", p_makeidParameter, p_modelidParameter, p_variantidParameter);
        }
    
        public virtual ObjectResult<SP_GETTOP10MODELBYMAKEID> SP_GETTOP10MODELBYMAKEID(Nullable<long> p_makeid)
        {
            var p_makeidParameter = p_makeid.HasValue ?
                new ObjectParameter("p_makeid", p_makeid) :
                new ObjectParameter("p_makeid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETTOP10MODELBYMAKEID>("SP_GETTOP10MODELBYMAKEID", p_makeidParameter);
        }
    
        public virtual ObjectResult<SP_GETTOP10VARIANTBYMODELID_Result> SP_GETTOP10VARIANTBYMODELID(Nullable<long> p_modelid, string p_fueltype)
        {
            var p_modelidParameter = p_modelid.HasValue ?
                new ObjectParameter("p_modelid", p_modelid) :
                new ObjectParameter("p_modelid", typeof(long));
    
            var p_fueltypeParameter = p_fueltype != null ?
                new ObjectParameter("p_fueltype", p_fueltype) :
                new ObjectParameter("p_fueltype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETTOP10VARIANTBYMODELID_Result>("SP_GETTOP10VARIANTBYMODELID", p_modelidParameter, p_fueltypeParameter);
        }
    
        public virtual int SP_POLICYDETAILSMASTER(string p_mode, string p_enquiryid, Nullable<long> p_companyid, Nullable<long> p_pospid, string p_custmertype, string p_policytype, string p_producttype, Nullable<bool> p_isrenewable, string p_customerfirstname, string p_customermiddlename, string p_customerlastname, string p_customeraddress, string p_customerpancardno, string p_customergstno, string p_customeremailid, Nullable<System.DateTime> p_customerdob, string p_customermobileno, Nullable<long> p_rtoid, Nullable<long> p_zoneid, Nullable<long> p_makeid, Nullable<long> p_modelid, Nullable<long> p_variantid, Nullable<System.DateTime> p_issuedate, Nullable<System.DateTime> p_registrationdate, Nullable<System.DateTime> p_manufacturdate, Nullable<int> p_seatingcapacity, string p_registrationno, Nullable<long> p_cubiccapacity, string p_engingno, string p_chassisno, string p_fueltype, string p_policyno, Nullable<System.DateTime> p_policystartdate, Nullable<System.DateTime> p_policyenddate, Nullable<System.DateTime> p_tpstartdate, Nullable<System.DateTime> p_tpenddate, Nullable<int> p_tenure, Nullable<int> p_ncdpercentage, Nullable<decimal> p_ncdpercentagevalue, Nullable<decimal> p_otherdiscount, Nullable<decimal> p_idv, Nullable<decimal> p_addonpremium, Nullable<decimal> p_odpremium, Nullable<decimal> p_tppremium, Nullable<decimal> p_netpremium, Nullable<decimal> p_gstvalue, Nullable<decimal> p_finalpremium, Nullable<bool> p_paymentstatus)
        {
            var p_modeParameter = p_mode != null ?
                new ObjectParameter("p_mode", p_mode) :
                new ObjectParameter("p_mode", typeof(string));
    
            var p_enquiryidParameter = p_enquiryid != null ?
                new ObjectParameter("p_enquiryid", p_enquiryid) :
                new ObjectParameter("p_enquiryid", typeof(string));
    
            var p_companyidParameter = p_companyid.HasValue ?
                new ObjectParameter("p_companyid", p_companyid) :
                new ObjectParameter("p_companyid", typeof(long));
    
            var p_pospidParameter = p_pospid.HasValue ?
                new ObjectParameter("p_pospid", p_pospid) :
                new ObjectParameter("p_pospid", typeof(long));
    
            var p_custmertypeParameter = p_custmertype != null ?
                new ObjectParameter("p_custmertype", p_custmertype) :
                new ObjectParameter("p_custmertype", typeof(string));
    
            var p_policytypeParameter = p_policytype != null ?
                new ObjectParameter("p_policytype", p_policytype) :
                new ObjectParameter("p_policytype", typeof(string));
    
            var p_producttypeParameter = p_producttype != null ?
                new ObjectParameter("p_producttype", p_producttype) :
                new ObjectParameter("p_producttype", typeof(string));
    
            var p_isrenewableParameter = p_isrenewable.HasValue ?
                new ObjectParameter("p_isrenewable", p_isrenewable) :
                new ObjectParameter("p_isrenewable", typeof(bool));
    
            var p_customerfirstnameParameter = p_customerfirstname != null ?
                new ObjectParameter("p_customerfirstname", p_customerfirstname) :
                new ObjectParameter("p_customerfirstname", typeof(string));
    
            var p_customermiddlenameParameter = p_customermiddlename != null ?
                new ObjectParameter("p_customermiddlename", p_customermiddlename) :
                new ObjectParameter("p_customermiddlename", typeof(string));
    
            var p_customerlastnameParameter = p_customerlastname != null ?
                new ObjectParameter("p_customerlastname", p_customerlastname) :
                new ObjectParameter("p_customerlastname", typeof(string));
    
            var p_customeraddressParameter = p_customeraddress != null ?
                new ObjectParameter("p_customeraddress", p_customeraddress) :
                new ObjectParameter("p_customeraddress", typeof(string));
    
            var p_customerpancardnoParameter = p_customerpancardno != null ?
                new ObjectParameter("p_customerpancardno", p_customerpancardno) :
                new ObjectParameter("p_customerpancardno", typeof(string));
    
            var p_customergstnoParameter = p_customergstno != null ?
                new ObjectParameter("p_customergstno", p_customergstno) :
                new ObjectParameter("p_customergstno", typeof(string));
    
            var p_customeremailidParameter = p_customeremailid != null ?
                new ObjectParameter("p_customeremailid", p_customeremailid) :
                new ObjectParameter("p_customeremailid", typeof(string));
    
            var p_customerdobParameter = p_customerdob.HasValue ?
                new ObjectParameter("p_customerdob", p_customerdob) :
                new ObjectParameter("p_customerdob", typeof(System.DateTime));
    
            var p_customermobilenoParameter = p_customermobileno != null ?
                new ObjectParameter("p_customermobileno", p_customermobileno) :
                new ObjectParameter("p_customermobileno", typeof(string));
    
            var p_rtoidParameter = p_rtoid.HasValue ?
                new ObjectParameter("p_rtoid", p_rtoid) :
                new ObjectParameter("p_rtoid", typeof(long));
    
            var p_zoneidParameter = p_zoneid.HasValue ?
                new ObjectParameter("p_zoneid", p_zoneid) :
                new ObjectParameter("p_zoneid", typeof(long));
    
            var p_makeidParameter = p_makeid.HasValue ?
                new ObjectParameter("p_makeid", p_makeid) :
                new ObjectParameter("p_makeid", typeof(long));
    
            var p_modelidParameter = p_modelid.HasValue ?
                new ObjectParameter("p_modelid", p_modelid) :
                new ObjectParameter("p_modelid", typeof(long));
    
            var p_variantidParameter = p_variantid.HasValue ?
                new ObjectParameter("p_variantid", p_variantid) :
                new ObjectParameter("p_variantid", typeof(long));
    
            var p_issuedateParameter = p_issuedate.HasValue ?
                new ObjectParameter("p_issuedate", p_issuedate) :
                new ObjectParameter("p_issuedate", typeof(System.DateTime));
    
            var p_registrationdateParameter = p_registrationdate.HasValue ?
                new ObjectParameter("p_registrationdate", p_registrationdate) :
                new ObjectParameter("p_registrationdate", typeof(System.DateTime));
    
            var p_manufacturdateParameter = p_manufacturdate.HasValue ?
                new ObjectParameter("p_manufacturdate", p_manufacturdate) :
                new ObjectParameter("p_manufacturdate", typeof(System.DateTime));
    
            var p_seatingcapacityParameter = p_seatingcapacity.HasValue ?
                new ObjectParameter("p_seatingcapacity", p_seatingcapacity) :
                new ObjectParameter("p_seatingcapacity", typeof(int));
    
            var p_registrationnoParameter = p_registrationno != null ?
                new ObjectParameter("p_registrationno", p_registrationno) :
                new ObjectParameter("p_registrationno", typeof(string));
    
            var p_cubiccapacityParameter = p_cubiccapacity.HasValue ?
                new ObjectParameter("p_cubiccapacity", p_cubiccapacity) :
                new ObjectParameter("p_cubiccapacity", typeof(long));
    
            var p_engingnoParameter = p_engingno != null ?
                new ObjectParameter("p_engingno", p_engingno) :
                new ObjectParameter("p_engingno", typeof(string));
    
            var p_chassisnoParameter = p_chassisno != null ?
                new ObjectParameter("p_chassisno", p_chassisno) :
                new ObjectParameter("p_chassisno", typeof(string));
    
            var p_fueltypeParameter = p_fueltype != null ?
                new ObjectParameter("p_fueltype", p_fueltype) :
                new ObjectParameter("p_fueltype", typeof(string));
    
            var p_policynoParameter = p_policyno != null ?
                new ObjectParameter("p_policyno", p_policyno) :
                new ObjectParameter("p_policyno", typeof(string));
    
            var p_policystartdateParameter = p_policystartdate.HasValue ?
                new ObjectParameter("p_policystartdate", p_policystartdate) :
                new ObjectParameter("p_policystartdate", typeof(System.DateTime));
    
            var p_policyenddateParameter = p_policyenddate.HasValue ?
                new ObjectParameter("p_policyenddate", p_policyenddate) :
                new ObjectParameter("p_policyenddate", typeof(System.DateTime));
    
            var p_tpstartdateParameter = p_tpstartdate.HasValue ?
                new ObjectParameter("p_tpstartdate", p_tpstartdate) :
                new ObjectParameter("p_tpstartdate", typeof(System.DateTime));
    
            var p_tpenddateParameter = p_tpenddate.HasValue ?
                new ObjectParameter("p_tpenddate", p_tpenddate) :
                new ObjectParameter("p_tpenddate", typeof(System.DateTime));
    
            var p_tenureParameter = p_tenure.HasValue ?
                new ObjectParameter("p_tenure", p_tenure) :
                new ObjectParameter("p_tenure", typeof(int));
    
            var p_ncdpercentageParameter = p_ncdpercentage.HasValue ?
                new ObjectParameter("p_ncdpercentage", p_ncdpercentage) :
                new ObjectParameter("p_ncdpercentage", typeof(int));
    
            var p_ncdpercentagevalueParameter = p_ncdpercentagevalue.HasValue ?
                new ObjectParameter("p_ncdpercentagevalue", p_ncdpercentagevalue) :
                new ObjectParameter("p_ncdpercentagevalue", typeof(decimal));
    
            var p_otherdiscountParameter = p_otherdiscount.HasValue ?
                new ObjectParameter("p_otherdiscount", p_otherdiscount) :
                new ObjectParameter("p_otherdiscount", typeof(decimal));
    
            var p_idvParameter = p_idv.HasValue ?
                new ObjectParameter("p_idv", p_idv) :
                new ObjectParameter("p_idv", typeof(decimal));
    
            var p_addonpremiumParameter = p_addonpremium.HasValue ?
                new ObjectParameter("p_addonpremium", p_addonpremium) :
                new ObjectParameter("p_addonpremium", typeof(decimal));
    
            var p_odpremiumParameter = p_odpremium.HasValue ?
                new ObjectParameter("p_odpremium", p_odpremium) :
                new ObjectParameter("p_odpremium", typeof(decimal));
    
            var p_tppremiumParameter = p_tppremium.HasValue ?
                new ObjectParameter("p_tppremium", p_tppremium) :
                new ObjectParameter("p_tppremium", typeof(decimal));
    
            var p_netpremiumParameter = p_netpremium.HasValue ?
                new ObjectParameter("p_netpremium", p_netpremium) :
                new ObjectParameter("p_netpremium", typeof(decimal));
    
            var p_gstvalueParameter = p_gstvalue.HasValue ?
                new ObjectParameter("p_gstvalue", p_gstvalue) :
                new ObjectParameter("p_gstvalue", typeof(decimal));
    
            var p_finalpremiumParameter = p_finalpremium.HasValue ?
                new ObjectParameter("p_finalpremium", p_finalpremium) :
                new ObjectParameter("p_finalpremium", typeof(decimal));
    
            var p_paymentstatusParameter = p_paymentstatus.HasValue ?
                new ObjectParameter("p_paymentstatus", p_paymentstatus) :
                new ObjectParameter("p_paymentstatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_POLICYDETAILSMASTER", p_modeParameter, p_enquiryidParameter, p_companyidParameter, p_pospidParameter, p_custmertypeParameter, p_policytypeParameter, p_producttypeParameter, p_isrenewableParameter, p_customerfirstnameParameter, p_customermiddlenameParameter, p_customerlastnameParameter, p_customeraddressParameter, p_customerpancardnoParameter, p_customergstnoParameter, p_customeremailidParameter, p_customerdobParameter, p_customermobilenoParameter, p_rtoidParameter, p_zoneidParameter, p_makeidParameter, p_modelidParameter, p_variantidParameter, p_issuedateParameter, p_registrationdateParameter, p_manufacturdateParameter, p_seatingcapacityParameter, p_registrationnoParameter, p_cubiccapacityParameter, p_engingnoParameter, p_chassisnoParameter, p_fueltypeParameter, p_policynoParameter, p_policystartdateParameter, p_policyenddateParameter, p_tpstartdateParameter, p_tpenddateParameter, p_tenureParameter, p_ncdpercentageParameter, p_ncdpercentagevalueParameter, p_otherdiscountParameter, p_idvParameter, p_addonpremiumParameter, p_odpremiumParameter, p_tppremiumParameter, p_netpremiumParameter, p_gstvalueParameter, p_finalpremiumParameter, p_paymentstatusParameter);
        }
    }
}
