//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_WISE_STATE_CITY_AREA_MASTER
    {
        public long id { get; set; }
        public Nullable<long> stateid { get; set; }
        public string statename { get; set; }
        public string statevalue { get; set; }
        public Nullable<long> cityid { get; set; }
        public string cityname { get; set; }
        public string cityvalue { get; set; }
        public string areaname { get; set; }
        public string areavalue { get; set; }
        public Nullable<long> companyid { get; set; }
        public Nullable<long> mstateid { get; set; }
        public Nullable<long> mcityid { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
