//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class icici_paymenttagging
    {
        public long id { get; set; }
        public string EnqNo { get; set; }
        public string TransactionId { get; set; }
        public string PaymentAmount { get; set; }
        public string CustomerID { get; set; }
        public string PayerType { get; set; }
        public string ProposalNo { get; set; }
        public string PolicyNo { get; set; }
        public string dealid { get; set; }
    }
}
