//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSURANCEVARIANTMASTER
    {
        public long mastervariant_id { get; set; }
        public Nullable<long> companyid { get; set; }
        public string variantname { get; set; }
        public Nullable<long> mastermd_id { get; set; }
        public Nullable<long> variantid { get; set; }
    }
}
