//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSURANCECOMPANY
    {
        public long id { get; set; }
        public string companyname { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string shortname { get; set; }
    }
}
