//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAKE_ANDAPP
    {
        public long makeid { get; set; }
        public string makename { get; set; }
        public Nullable<bool> istopmake { get; set; }
        public Nullable<long> showingorder { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<bool> haslogo { get; set; }
    }
}
