//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODEL_ANDAPP
    {
        public long modelid { get; set; }
        public string modelname { get; set; }
        public string aliasmodelname { get; set; }
        public Nullable<bool> istopmodel { get; set; }
        public string modelname_v2 { get; set; }
        public Nullable<long> makeid { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
    }
}
