//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Parameter
    {
        public int id { get; set; }
        public string enq_id { get; set; }
        public Nullable<int> com_id { get; set; }
        public string parameter_name { get; set; }
        public string parameter_value { get; set; }
    }
}
