//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLICY_ENQUIRY
    {
        public long enquiryid { get; set; }
        public string enquiryno { get; set; }
        public string enquiryrequest { get; set; }
        public string enquiryresponse { get; set; }
        public string firstquote { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<long> enquiryby { get; set; }
        public Nullable<int> enquirytype { get; set; }
    }
}
