//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PospCity_Mapping
    {
        public long id { get; set; }
        public Nullable<long> rtoid { get; set; }
        public Nullable<long> stateid { get; set; }
        public string rtocode { get; set; }
        public string rtodesc { get; set; }
        public Nullable<long> cityid { get; set; }
    }
}
