//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    
    public partial class SP_COMPANY_WISE_NOMINEERELATION_Result1
    {
        public int id { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public Nullable<int> comid { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
