//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    
    public partial class SP_QUALIFYCOMPANY
    {
        public string comid { get; set; }
        public string comname { get; set; }
        public string makecode { get; set; }
        public string makename { get; set; }
        public string modelcode { get; set; }
        public string modelname { get; set; }
        public string variantcode { get; set; }
        public string variantname { get; set; }
        public string cc { get; set; }
        public string fuel { get; set; }
        public string sc { get; set; }
        public string segment { get; set; }
        public string bodytype { get; set; }
    }
}
