//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VARIANT_ANDAPP
    {
        public long variantid { get; set; }
        public string variantname { get; set; }
        public Nullable<long> modelid { get; set; }
        public string fueltype { get; set; }
        public string transmissiontype { get; set; }
        public Nullable<int> cc { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
    }
}
