//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GENERATEDQUOTAIONLIST_POSPWISE
    {
        public long enquiryid { get; set; }
        public string enquiryno { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<long> enquiryby { get; set; }
        public string insurancename { get; set; }
        public string MakeName { get; set; }
        public string ModelName { get; set; }
        public string VariantId { get; set; }
        public string registrationno { get; set; }
        public string Company { get; set; }
        public string NetPremiumC { get; set; }
        public long modelid { get; set; }
        public long makeid { get; set; }
        public string VariantId1 { get; set; }
    }
}
