//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TOP10MAKE
    {
        public long id { get; set; }
        public Nullable<long> makeid { get; set; }
        public Nullable<int> MOST_FREQUENT { get; set; }
        public string makename { get; set; }
        public Nullable<bool> haslogo { get; set; }
    }
}
