//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndWebApi.FGI_Policy_Pdf {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FGI_Policy_Pdf.PDFSoap")]
    public interface PDFSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPDF(string PolicyNumber, string UserID, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPDF", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetPDFAsync(string PolicyNumber, string UserID, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEndNotePDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetEndNotePDF(string PolicyNumber, string UserID, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEndNotePDF", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetEndNotePDFAsync(string PolicyNumber, string UserID, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRenewalPDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetRenewalPDF(string PolicyNumber, string month, string UserID, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRenewalPDF", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetRenewalPDFAsync(string PolicyNumber, string month, string UserID, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PDFSoapChannel : AndWebApi.FGI_Policy_Pdf.PDFSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PDFSoapClient : System.ServiceModel.ClientBase<AndWebApi.FGI_Policy_Pdf.PDFSoap>, AndWebApi.FGI_Policy_Pdf.PDFSoap {
        
        public PDFSoapClient() {
        }
        
        public PDFSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PDFSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PDFSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PDFSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetPDF(string PolicyNumber, string UserID, string Password) {
            return base.Channel.GetPDF(PolicyNumber, UserID, Password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetPDFAsync(string PolicyNumber, string UserID, string Password) {
            return base.Channel.GetPDFAsync(PolicyNumber, UserID, Password);
        }
        
        public System.Data.DataTable GetEndNotePDF(string PolicyNumber, string UserID, string Password) {
            return base.Channel.GetEndNotePDF(PolicyNumber, UserID, Password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetEndNotePDFAsync(string PolicyNumber, string UserID, string Password) {
            return base.Channel.GetEndNotePDFAsync(PolicyNumber, UserID, Password);
        }
        
        public System.Data.DataTable GetRenewalPDF(string PolicyNumber, string month, string UserID, string Password) {
            return base.Channel.GetRenewalPDF(PolicyNumber, month, UserID, Password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetRenewalPDFAsync(string PolicyNumber, string month, string UserID, string Password) {
            return base.Channel.GetRenewalPDFAsync(PolicyNumber, month, UserID, Password);
        }
    }
}
